C V6P0 : 
C CV pour Rebekka : Augmenter la valeur de NSICLM de 10 à 20
C AC(NSICLM), CALAC
C
CV 15/03/09: rajout des 3 variables MU, KS, KSP, KSR
CCV 18/07/09: VITCE et VITCD sont des constantes
CJMH 13/08/09 IT5 SUPPRIME
      MODULE DECLARATIONS_SISYPHE
C
C
C***********************************************************************
C
C                          SISYPHE VERSION 6.0
C 
C***********************************************************************
C
        USE BIEF_DEF
C
C       NOTE: THIS MODULE IS ORGANISED IN 10 PARTS
C
C       1) VECTORS (WILL BE DECLARED AS BIEF_OBJ STRUCTURES)
C       2) MATRICES (WILL BE DECLARED AS BIEF_OBJ STRUCTURES) 
C       3) BLOCKS (WILL BE DECLARED AS BIEF_OBJ STRUCTURES)
C       4) INTEGERS
C       5) LOGICAL VALUES
C       6) REALS
C       7) STRINGS
C       8) SLVCFG STRUCTURES
C       9) MESH STRUCTURE
C      10) ALIASES    
C
C-----------------------------------------------------------------------
C
C       1) VECTORS
C
C-----------------------------------------------------------------------
C
C     EVOLUTION
      TYPE(BIEF_OBJ), TARGET :: E

C     EVOLUTION SAVED FOR CONSTANT FLOW DISCHARGE
      TYPE(BIEF_OBJ), TARGET :: ECPL

C     FREE SURFACE LEVEL, AND INCREMENT WHEN READING AN HYDRO FILE
      TYPE(BIEF_OBJ), TARGET :: Z, DEL_Z

C     EVOLUTION DUE TO BEDLOAD, SUSPENSION
      TYPE(BIEF_OBJ), TARGET :: ZF_C,ZF_S

C     CUMULATED EVOLUTION
      TYPE(BIEF_OBJ), TARGET :: ESOMT

C     MAXIMUM EVOLUTION
      TYPE(BIEF_OBJ), TARGET :: EMAX
        
C     COMPONENTS OF FLOW RATE, AND INCREMENTS WHEN READING AN HYDRO FILE
      TYPE(BIEF_OBJ), TARGET :: QU,QV, DEL_QU,DEL_QV

C     FLOW RATE
      TYPE(BIEF_OBJ), TARGET :: Q

C     SOLID DISCHARGE
      TYPE(BIEF_OBJ), TARGET :: QS  , QSX , QSY
      TYPE(BIEF_OBJ), TARGET :: QS_C, QSXC, QSYC
      TYPE(BIEF_OBJ), TARGET :: QS_S, QSXS, QSYS     

C     WATER DEPTH
      TYPE(BIEF_OBJ), TARGET :: HN,HCLIP,U2D,V2D,UNORM

C     WATER DEPTH SAVED FOR CONSTANT FLOW DISCHARGE
      TYPE(BIEF_OBJ), TARGET :: HCPL
C
C     VALUES ON BOUNDARIES: E, QS, ZF
      TYPE(BIEF_OBJ), TARGET :: EBOR,QBOR,FLBOR

C     BOTTOM LEVEL
      TYPE(BIEF_OBJ), TARGET :: ZF

C     NON ERODABLE BOTTOM LEVEL 
      TYPE(BIEF_OBJ), TARGET :: ZR
        
C     REFERENCE ELEVATION
      TYPE(BIEF_OBJ), TARGET :: ZREF

C     INTEGRAL OF BASES, IN PARALLEL AND THEIR INVERSE
      TYPE(BIEF_OBJ), TARGET :: VOLU2D, V2DPAR, UNSV2D
        
C     FRICTION COEFFICIENT
      TYPE(BIEF_OBJ), TARGET :: CHESTR

C     ANGLE BETWEEN QS AND Q
      TYPE(BIEF_OBJ), TARGET :: CALFA,SALFA
  
C     VOID STRUCTURE
      TYPE(BIEF_OBJ), TARGET :: S

C     MASQUES
      TYPE(BIEF_OBJ), TARGET :: MASKPT,MASKTR,MASKB
      TYPE(BIEF_OBJ), TARGET :: MASKEL, MSKTMP

C     W1 WORKING ARRAYS
      TYPE(BIEF_OBJ), TARGET :: W1

! WAVE DATA
! -------- 
C     ANGLE DE LA HOULE AVEC L'AXE OX
      TYPE(BIEF_OBJ), TARGET :: THETAW

C     COEFFICIENT DE FROTTEMENT HOULE
      TYPE(BIEF_OBJ), TARGET :: FW

C     VITESSE ORBITALE
      TYPE(BIEF_OBJ), TARGET :: UW

C     HAUTEUR SIGNIFICATIVE DE HOULE, PERIODE MOYENNE  
      TYPE(BIEF_OBJ), TARGET :: HW,TW  

C     INDIC,IFAMAS
      TYPE(BIEF_OBJ), TARGET :: INDIC,IFAMAS

C     INTEGER WORKING ARRAY
      TYPE(BIEF_OBJ), TARGET :: IT1,IT2,IT3,IT4

C     TYPE OF BOUNDARY CONDITIONS
      TYPE(BIEF_OBJ), TARGET :: LIEBOR,LIQBOR,LIMTEC

C     INFLUENCE DE L'EFFET DE PENTE SUR L'AMPLITUDE       
      TYPE(BIEF_OBJ), TARGET :: COEFPN

C     LIQUID BOUNDARIES NUMBERING
      TYPE(BIEF_OBJ), TARGET :: NUMLIQ

      TYPE(BIEF_OBJ), TARGET :: TOB,CF,TOBW
C
      TYPE(BIEF_OBJ), TARGET :: MU,KS,KSP,KSR
     
C     BED LEVEL CHANGE FOR GRAIN-FEEDING
      TYPE(BIEF_OBJ), TARGET :: DZF_GF

! NONEQUILIBRIUM BED LOAD AND NONUNIFORM BED MATERIA (BMD and MGDL)
! -----------------------------------------------------------------    
C     DM OF ACTIVE-LAYER AND UNDER-LAYER
      TYPE(BIEF_OBJ), TARGET :: ACLADM
      TYPE(BIEF_OBJ), TARGET :: UNLADM

C     NUMBER OF LAYERS
C     INTEGER NLAYER(NPOINM)
      TYPE(BIEF_OBJ), TARGET :: NLAYER

C     HIDING FACTOR FOR PARTICULAR SIZE CLASS
      TYPE(BIEF_OBJ), TARGET :: HIDING
C
C     DOUBLE PRECISION ELAY(NPOINM)
      TYPE(BIEF_OBJ), TARGET :: ELAY
C
C     ACTIVE STRATUM THICKNESS
      TYPE(BIEF_OBJ), TARGET :: ESTRAT
C
! SUSPENSION  (F. Menard)
! -----------------------
C     FLUX DE DEPOT
      TYPE(BIEF_OBJ), TARGET :: FLUDP, FLUDPT
C
C     FLUX DE DEPOT
      TYPE(BIEF_OBJ), TARGET :: FLUER, FLUERT
C
C     CONCENTRATION AU TEMPS N : CS
C     CONCENTRATION AUX POINTS DE BORD (DIM.NPTFR) : CBOR
      TYPE(BIEF_OBJ), TARGET :: CS, CST, CTILD, CBOR, CSTAEQ
C     CONCENTRATION EN G/L: CSGL        
      TYPE(BIEF_OBJ), TARGET :: CSGL         
C     COORDONNEES DES VECTEURS VITESSE.
      TYPE(BIEF_OBJ), TARGET ::  UCONV ,VCONV
C
C     HAUTEUR DE PROPAGATION
      TYPE(BIEF_OBJ), TARGET :: HPROP
C
      TYPE(BIEF_OBJ), TARGET :: DISP,DISP_C
      TYPE(BIEF_OBJ), TARGET :: AFBOR  , BFBOR
C     FLUX AUX BORDS 
      TYPE(BIEF_OBJ), TARGET :: FLBOR_SIS,FLBORTRA
C
C     CONDITIONS AUX LIMITES SUR LE SEDIMENT               : LICBOR
C     TYPES DE CONDITIONS AUX LIMITES SUR H                : LIHBOR
C     TYPES DE CONDITIONS AUX LIMITES POUR LA PROPAGATION  : LIMPRO
C                PAR POINTS   :    .1:H  .2:U  .3:V
C                PAR SEGMENTS :    .4:H  .5:U  .6:V
      TYPE(BIEF_OBJ), TARGET :: LIMDIF,LIMPRO,LICBOR,LIHBOR
C     DERNIERE LIGNE DU FICHIER DES CONDITIONS AUX LIMITES
      TYPE(BIEF_OBJ), TARGET :: BOUNDARY_COLOUR
C
C     COND. AUX LIM. DU TRACEUR POUR LE CALCUL (LITBOR MODIFIES): CLT         
C     TYPES DE CONDITIONS AUX LIMITES SUR H,U,V : CLU, CLV
      TYPE(BIEF_OBJ), TARGET :: CLT, CLU, CLV 
C
C     TABLEAUX DE TRAVAIL SUR LES ELEMENTS
      TYPE(BIEF_OBJ), TARGET :: TE1 , TE2 , TE3

C     COEFF DU TENSEUR  DE DISPERSION (DIM. NPOIN)
      TYPE(BIEF_OBJ), TARGET :: KX, KY, KZ

C     TABLEAU POUR INDIQUER SI LE FOND NON ERDOABLE EST ATTEINT (POUR VF)
      TYPE(BIEF_OBJ), TARGET :: BREACH
C
C     POUR LES SEDIMENTS MIXTES
      TYPE(BIEF_OBJ), TARGET :: FLUER_VASE,TOCE_MIXTE,MS_SABLE,MS_VASE
C
C-----------------------------------------------------------------------
C
C       2) MATRICES
C
C-----------------------------------------------------------------------
C
      TYPE(BIEF_OBJ), TARGET :: MBOR
      TYPE(BIEF_OBJ), TARGET :: AM1_S,AM2_S

C
C-----------------------------------------------------------------------
C
C       3) BLOCKS
C
C-----------------------------------------------------------------------
C
C
C       BLOCK OF MASKS
        TYPE(BIEF_OBJ), TARGET :: MASK
C
C       BLOCK OF WORKING ARRAYS
        TYPE(BIEF_OBJ), TARGET :: TB
C
C       BLOCK OF PRIVATE VECTORS
        TYPE(BIEF_OBJ), TARGET :: PRIVE
C
C       BLOCK OF CLANDEST INE VARIABLES
        TYPE(BIEF_OBJ), TARGET :: VARCL
C
C       BLOCK OF VARIABLES FOR INPUT
        TYPE(BIEF_OBJ), TARGET :: VARHYD
C
C       BLOCK OF VARIABLES FOR OUTPUT
        TYPE(BIEF_OBJ), TARGET :: VARSOR
C
C       SEDIMENT FRACTION (nlaymax,nclass,npoin)
C       nlaymax may change during the computation
C       SEDIMENT COMPOSITION
        DOUBLE PRECISION,DIMENSION(:,:,:),TARGET,ALLOCATABLE::AVAIL
        TYPE(BIEF_OBJ), TARGET :: AVAI
C       LAYER THICKNESSES AS BIEF_OBJ
        TYPE(BIEF_OBJ), TARGET :: LAYTHI
C
        TYPE(BIEF_OBJ), TARGET :: QSCL  , QSCLX , QSCLY
        TYPE(BIEF_OBJ), TARGET :: QSCL_C, QSCLXC, QSCLYC
        TYPE(BIEF_OBJ), TARGET :: QSCL_S, QSCLXS, QSCLYS
        TYPE(BIEF_OBJ), TARGET :: ZFCL  , ZFCL_C, ZFCL_S
C
C-----------------------------------------------------------------------
C
C       4) INTEGERS
C
C-----------------------------------------------------------------------
C
C       KEY-WORDS AND PARAMETERS
C
C     MAXIMUM DE VARIABLES DE SORTIE
      INTEGER, PARAMETER :: MAXVAR = 100
C     MAXIMUM DE (NOMBRE DE FRONTIERES LIQUIDES, NOMBRE DE FRONTIERES SOLIDES)
      INTEGER, PARAMETER :: MAXFRO = 300
      INTEGER NFRLIQ,NFRSOL,DEBLIQ(MAXFRO),FINLIQ(MAXFRO)
      INTEGER DEBSOL(MAXFRO),FINSOL(MAXFRO)
C
C     MOT-CLE : OPTION POUR LA DIFFUSION DU TRACEUR
      INTEGER OPDTRA
C
      INTEGER OPTDIF
C       
C     OPTION DE SUPG 
      INTEGER OPTSUP 

C     NOMBRE DE PAS DE TEMPS TEMPS A EFFECTUER EN CONSTANT FLOW DISCHARGE
      INTEGER :: NCONDIS
C
      INTEGER KFROT,ICF,NPAS,NMAREE,LEOPR,LISPR, NVARCL
      INTEGER IELMT,IELMH_SIS,IELMU_SIS,IELMX
      INTEGER STDGEO ,LOGDES ,LOGPRE ,OPTBAN ,LVMAC 
      INTEGER HYDRO  ,OPTASS, NSOUS 
      INTEGER MARDAT(3),MARTIM(3),PRODUC
      INTEGER CHOIX , LT ,PTINIL, PTINIG,NPRIV, PERCOU
C
      INTEGER RESOL
      INTEGER DEPER
C
      INTEGER DEVIA, SLOPEFF
C
      !
      ! NONEQUILIBRIUM BED LOAD AND NONUNIFORM BED MATERIA (BMD and MGDL)
      ! -----------------------------------------------------------------    
C     MAXIMUM OF NUMBER OF SIZE-CLASSES
CV 04/05/2010
      INTEGER, PARAMETER :: NSICLM = 10
C
C     NUMBER OF SIZE-CLASSES
      INTEGER :: NSICLA
C
C     MAXIMUM NUMBER OF LAYER ON THE MESH
      INTEGER,PARAMETER :: NLAYMAX = 10
C
C     NUMBER OF POSSIBLE BED-LOAD MODEL LAYERS
      INTEGER NOMBLAY
C
C     FORMULE POUR LE HIDING FACTOR
      INTEGER HIDFAC
C
      INTEGER, PARAMETER :: tmcod_sistel = 0
C
C     FOR NON EQUILIBIRUM BED-LOD
      INTEGER :: LOADMETH
C
C     DEBUGEUR
      INTEGER :: DEBUG
C      
      ! EQUILIBRIUM CONC
      INTEGER :: ICQ
C 
      ! NUMBER OF CONTROL SECTIONS POINTS
      INTEGER NCP     
      ! ARRAY CONTAINING THE GLOBAL NUMBER OF POINTS OF CONTROL SECTIONS
      INTEGER, ALLOCATABLE :: CTRLSC(:)
C
C     ORIGIN COORDINATES
C
      INTEGER I_ORIG,J_ORIG
C
C     NOMBRE DE COUCHES POUR LE TASSEMENT    
C
      INTEGER NCOUCH_TASS
!
C     PREDICTEUR DE RIDES    
C
      INTEGER ICR
!      
! -----------------------------------------------------------------------
! -----------------------------------------------------------------------
!
!       5) LOGICAL VALUES
!
! -----------------------------------------------------------------------
! -----------------------------------------------------------------------
      ! IMPRESSION DES VARIABLE EN LISTING OU GRAPHIQUE
      LOGICAL :: SORLEO(100), SORIMP(100)

      ! PRISE EN COMPTE DU MASQUE
      LOGICAL :: MSK

      ! DECISION DE L'IMPRESSION
      LOGICAL :: ENTET

      ! INFORME SI LA RESOLUTION POUR LA SUSPENSION EST IMPLICITE
      LOGICAL :: YASMI

      ! MOTS-CLE
      ! --------
      LOGICAL :: SPHERI        ! EQUATIONS SPHERIQUES (CODEES EN DUR)
      LOGICAL :: PERMA         ! HYDRODYNAMIQUE PERMANENTE
      LOGICAL :: BANDEC        ! BANCS DECOUVRANTS
      LOGICAL :: HOULE         ! HOULE
      LOGICAL :: CALWC         ! VITESSE DE CHUTE (CODE PARTIELLEMENT EN DUR)
      LOGICAL :: CALAC         ! PARAMETRE DE SHIELDS
      LOGICAL :: CHARR         ! CHARRIAGE
      LOGICAL :: NOEQUBED      ! LOADING LAW USED OR NOT
      LOGICAL :: VF            ! FINITE VOLUME
      LOGICAL :: LUMPI         ! MASS-LUMPING
      LOGICAL :: LCONDIS       ! CONSTANT FLOW DISCHARGE
      LOGICAL :: LGRAFED       ! GRAIN-FEEDING
      LOGICAL :: CONST_ALAYER  ! EPAISSEUR DE LA COUCHE ACTIVE CONSTANTE
      LOGICAL :: SUSP          ! SUSPENSION
      LOGICAL :: BILMA         ! BILAN DE MASSE
      LOGICAL :: VALID         ! VALIDATION
      LOGICAL :: IMP_INFLOW_C  ! imposed concentration in inflow
      LOGICAL :: SECCURRENT    ! Courants secondaires
      LOGICAL :: UNIT          ! UNITE
      LOGICAL :: CORR_CONV     ! prise en compte du champ convecteur
      LOGICAL :: DEBU          ! pour suite de calcul
      LOGICAL :: DIFT          ! diffusion de la concentration en suspension
      LOGICAL :: SLIDE         ! glissement du sediment
      LOGICAL :: SEDCO(NSICLM) ! sediment non cohesif pour chaque classe 
!  CV    
      LOGICAL :: TASS          ! Prise en compte du tassement 
      LOGICAL :: MIXTE         ! Sediments mixtes
      LOGICAL :: DREDGESIM     ! Couplage avec DredgeSim
C
C-----------------------------------------------------------------------
C
C       6) REALS
C
C-----------------------------------------------------------------------
C
      DOUBLE PRECISION RC   ,XMVE  ,XMVS    ,XKV   
CV 04/05/2010      AC (NSICLM)
      DOUBLE PRECISION SFON ,GRAV  ,VCE   ,HMIN  ,TETA
      DOUBLE PRECISION BETA ,DELT  ,PMAREE ,TPREC ,PHI0,DT 
!
      ! CRITERIA FOR NEW FLOW CALCULATION WITH FLOW CONSTANT DISCHARGE
      DOUBLE PRECISION :: CRIT_CFD
!
      DOUBLE PRECISION :: FRACSED_GF(NSICLM),CS0(NSICLM)
!
C     MASSOU : MASSE ECHANGEE PAR TERME SOURCE
      DOUBLE PRECISION MASSOU
      DOUBLE PRECISION CSF_VASE, CSF_SABLE
C
      DOUBLE PRECISION XWC(NSICLM),AC(NSICLM)
CV      DOUBLE PRECISION XWC(NSICLM),AC
C 
      DOUBLE PRECISION TETA_SUSP
C
      DOUBLE PRECISION  XKX, XKY
C Modifs MGDL (11/05)
      DOUBLE PRECISION PHISED, BETA2
C
      ! NONEQUILIBRIUM BED LOAD AND NONUNIFORM BED MATERIA (BMD and MGDL)
      ! -----------------------------------------------------------------    
C       HIDING FACTOR WHEN THE USER SUBROUTINE INIT_HIDING IS NOT USED
        DOUBLE PRECISION HIDI(NSICLM)
        DOUBLE PRECISION VSET(NSICLM)
        DOUBLE PRECISION FD90(NSICLM)
        DOUBLE PRECISION FDM(NSICLM)

C       INITIAL SEDIMENT COMPOSITION WHEN INIT_COMPO IS NOT USED
        DOUBLE PRECISION AVA0(NSICLM)

C       ACTIVE LAYER THICKNESS 
C       ELAYO=FIXED VALUE , ELAY=REAL VALUE FOR EACH POINT
C       WHEN ENOUGH SEDIMENT, ELAY = ELAY0 
        DOUBLE PRECISION ELAY0

C       VOLUME TOTAL DE SEDIMENT PAR CLASSE
        DOUBLE PRECISION VOLTOT(10)
C      
C       VITESSE POUR LA FROMULE DE KRONE ET PARTHENIADES
        DOUBLE PRECISION :: VITCD, VITCE

C       BILAN DE MASSE EN SUSPENSION
        DOUBLE PRECISION :: MASED0(NSICLM), MASINI(NSICLM)
        DOUBLE PRECISION :: MASTEN(NSICLM), MASTOU(NSICLM)
        DOUBLE PRECISION :: MASTCP(NSICLM), MASFIN(NSICLM)
        DOUBLE PRECISION :: MASDEP(NSICLM), MASDEPT(NSICLM)

C       LAYER THICKNESSES AS DOUBLE PRECISION 
        DOUBLE PRECISION,DIMENSION(:,:),TARGET,ALLOCATABLE :: ES
C
C       FOR NON EQUILIBIRUM BED-LOD
        DOUBLE PRECISION :: LS0
C
C       RATIO BETWEEN SKIN FRICTION AND MEAN DIAMETER
        DOUBLE PRECISION :: KSPRATIO
C       CONSTANTE DE KARIM, HOLLY & YANG
        DOUBLE PRECISION :: KARIM_HOLLY_YANG
C       CONSTANTE DE KARMAN
        DOUBLE PRECISION :: KARMAN
C       CONSTANTE DE PARTHENIADES
        DOUBLE PRECISION :: PARTHENIADES
C       CONCENTRATION MAXIMALE
        DOUBLE PRECISION :: CMAX
C       PI
        DOUBLE PRECISION :: PI

      ! ZERO DU CODE
      DOUBLE PRECISION :: ZERO      
      DOUBLE PRECISION :: BIJK
!     CONCENTRATIONS DE VASE PAR CLASSE AUX FRONTIERES       
      DOUBLE PRECISION :: CBOR_CLASSE(10*MAXFRO)
!     CONCENTRATIONS DE VASE PAR COUCHE      
      DOUBLE PRECISION :: CONC_VASE(10)
!     TRANSFERT DE MASSE ENTRE COUCHES     
      DOUBLE PRECISION :: TRANS_MASS(10)
!     CONTRAINTE CRITIQUE D'EROSION DE LA VASE PAR COUCHES    
      DOUBLE PRECISION :: TOCE_VASE(10)
C
C-----------------------------------------------------------------------
C
C       7) STRINGS
C
C-----------------------------------------------------------------------
C
      CHARACTER(LEN=72)  TITCA,SORTIS,VARIM
      CHARACTER(LEN=3)   BINGEOSIS,BINPRESIS,BINHYDSIS
      CHARACTER(LEN=3)   BINRESSIS,BINREFSIS
      CHARACTER(LEN=32)  VARCLA(10),TEXTE(MAXVAR),TEXTPR(MAXVAR)
      CHARACTER(LEN=20)  EQUA
      CHARACTER(LEN=8)   MNEMO(100)      
      CHARACTER(LEN=144) COUPLINGSIS
C
C-----------------------------------------------------------------------
C
C       8) SLVCFG STRUCTURES
C
C-----------------------------------------------------------------------
C
      TYPE(SLVCFG) :: SLVSED
      TYPE(SLVCFG) :: SLVTRA
C
C-----------------------------------------------------------------------
C
C       9) MESH STRUCTURE
C
C-----------------------------------------------------------------------
C
      TYPE(BIEF_MESH) :: MESH
C
C-----------------------------------------------------------------------
C
C      10) ALIASES
C
C-----------------------------------------------------------------------
C
C       DECLARATION OF POINTERS FOR ALIASES.
C       TARGETS ARE DEFINED IN POINT_TELEMAC2D.
C
C       ALIASES FOR WORKING VECTORS IN TB
        TYPE(BIEF_OBJ),POINTER :: T1,T2,T3,T4,T5,T6,T7,T8
        TYPE(BIEF_OBJ),POINTER :: T9,T10,T11,T12,T13,T14
C
C       USEFUL COMPONENTS IN STRUCTURE MESH
        TYPE(BIEF_OBJ),   POINTER :: IKLE
        DOUBLE PRECISION, DIMENSION(:), POINTER :: X,Y 
        INTEGER, POINTER          :: NELEM
        INTEGER, POINTER          :: NELMAX
        INTEGER, POINTER          :: NPTFR
        INTEGER, POINTER          :: NPTFRX
        INTEGER, POINTER          :: DIM
        INTEGER, POINTER          :: TYPELM
        INTEGER, POINTER          :: NPOIN
        INTEGER, POINTER          :: NPMAX
        INTEGER, POINTER          :: MXPTVS
        INTEGER, POINTER          :: MXELVS
        INTEGER, POINTER          :: LV
C
C-----------------------------------------------------------------------
C
C      11) SISYPHE FILES + INTEGER DECLARATION FOR MED APPROACH
C
C-----------------------------------------------------------------------
C
C       MAXIMUM RANK OF LOGICAL UNITS AS DECLARED IN 
C       SUBMIT STRINGS IN THE DICTIONARY
        INTEGER, PARAMETER :: MAXLU_SIS = 46 !jaj #### 44->46
C
        TYPE(BIEF_FILE) :: SIS_FILES(MAXLU_SIS)
        INTEGER SISRES,SISREF,SISPRE,SISHYD,SISCOU,SISGEO,SISCLI
        INTEGER SISCAS,SISFON,SISMAF,SISSEC,SISSEO
C
C-----------------------------------------------------------------------
C !jaj ####
C      12) sections
C
C-----------------------------------------------------------------------
C
      TYPE (CHAIN_TYPE), ALLOCATABLE :: CHAIN(:)
C
C
C-----------------------------------------------------------------------
C
C  13) SANDSLIDE RELATED VARS
C
C-----------------------------------------------------------------------
      TYPE(NEIGHB), ALLOCATABLE :: ELEM(:)
      TYPE(NEIGHB_ELEMENTS), ALLOCATABLE :: NEIGHB_ELEM(:)
      TYPE(NEIGHB_GRAD), ALLOCATABLE :: NEIGHB_DIFF(:)
      INTEGER SLIDETYPE
C
C-----------------------------------------------------------------------
C
        SAVE   ! tres important
C
      END MODULE DECLARATIONS_SISYPHE
