C     *****************************
      MODULE DECLARATIONS_TELEMAC2D
C     *****************************
C
C***********************************************************************
C TELEMAC 2D VERSION 6.0
C***********************************************************************
C   
C  DECLARATION OF GLOBAL DATA STRUCTURE IN TELEMAC-2D
C
C***********************************************************************
C
        USE BIEF_DEF
        USE FRICTION_DEF
C
C       NOTE: THIS MODULE IS ORGANISED IN 10 PARTS
C
C      01) VECTORS (WILL BE DECLARED AS BIEF_OBJ STRUCTURES)
C      02) MATRICES (WILL BE DECLARED AS BIEF_OBJ STRUCTURES) 
C      03) BLOCKS (WILL BE DECLARED AS BIEF_OBJ STRUCTURES)
C      04) INTEGERS
C      05) LOGICAL VALUES
C      06) REALS
C      07) STRINGS
C      08) SLVCFG STRUCTURES
C      09) MESH STRUCTURE
C      10) ALIASES    
C
C
C       ALL BIEF_OBJ AND BIEF_MESH STRUCTURES ARE ALLOCATED
C       IN SUBROUTINE POINT_TELEMAC2D
C
C-----------------------------------------------------------------------
C
C       1) VECTORS
C
C-----------------------------------------------------------------------
C
C       COMPONENTS OF VELOCITY
C
        TYPE(BIEF_OBJ), TARGET :: U,V
C
C       DEPTH AT NEW TIME-STEP
C
        TYPE(BIEF_OBJ), TARGET :: H
C
C       TRACER AT NEW TIME-STEP
C
        TYPE(BIEF_OBJ), TARGET :: T
C
C       K AND EPSILON AT NEW TIME-STEP
C
        TYPE(BIEF_OBJ), TARGET :: AK,EP
C
C       U,V,H,T,AK AND EP AFTER ADVECTION BY CHARACTERISTICS
C
        TYPE(BIEF_OBJ), TARGET :: UTILD,VTILD,HTILD,TTILD,AKTILD,EPTILD
C
C       U,V,H,T,AK AND EP AT OLD TIME-STEP
C
        TYPE(BIEF_OBJ), TARGET :: UN,VN,HN,TN,AKN,EPN
C
C       INCREMENT OF H,U,V AND HN IN ONE TIME STEP
C
        TYPE(BIEF_OBJ), TARGET :: DH,DU,DV,DHN
C
C       COMPONENTS OF ADVECTING FIELD
C
        TYPE(BIEF_OBJ), TARGET :: UCONV , VCONV
C
C       DEPTH IN THE PROPAGATION TERM I.E. IN H DIV(U)
C  
        TYPE(BIEF_OBJ), TARGET :: HPROP
C
C       VALUES ON BOUNDARIES: U,V, WALL FRICTION, H,T,K,EP
C  
        TYPE(BIEF_OBJ), TARGET :: UBOR,VBOR,AUBOR,HBOR,TBOR,KBOR,EBOR
C
C       FLUXES ON THE BOUNDARIES
C  
        TYPE(BIEF_OBJ), TARGET :: FLBOR,FLBORTRA
C
C       ON BOUNDARIES: COEFFICIENTS FOR HEAT FLUXES
C  
        TYPE(BIEF_OBJ), TARGET :: ATBOR,BTBOR
C
C       ADIMENSIONAL FRICTION COEFFICIENTS
C
        TYPE(BIEF_OBJ), TARGET :: CF,CFBOR
C
C       VOID STRUCTURE
C  
        TYPE(BIEF_OBJ), TARGET :: S
C
C       BOTTOM TOPOGRAPHY, PER POINT, PER ELEMENTS
C     
        TYPE(BIEF_OBJ), TARGET :: ZF,ZFE
C
C       VELOCITY DIFFUSIVITY, TRACER DIFFUSIVITY, AND VEL. DIF. SAVED
C
        TYPE(BIEF_OBJ), TARGET :: VISC,VISCT,VISC_S
C
C       SOURCE TERMS IN THE MOMENTUM EQUATION
C
        TYPE(BIEF_OBJ), TARGET :: FU,FV
C
C       INITIAL CELERITY OF WAVES, INITIAL DEPTH
C
        TYPE(BIEF_OBJ), TARGET :: C0,H0
C
C       MASK FOR TRACER
C
        TYPE(BIEF_OBJ), TARGET :: MASKTR
C
C       FREE SURFACE ELEVATION OF INCIDENT WAVE
C
        TYPE(BIEF_OBJ), TARGET :: COTOND
C
C       ATMOSPHERIC PRESSURE, WIND VELOCITY
C
        TYPE(BIEF_OBJ), TARGET :: PATMOS,WINDX,WINDY
C
C       DENSITY
C
        TYPE(BIEF_OBJ), TARGET :: RO
C
C       FOR INTEGRAL OF BASES, IN PARALLEL AND THEIR INVERSE
C
        TYPE(BIEF_OBJ), TARGET :: VOLU2D,V2DPAR,UNSV2D
C
C       RIGHT HAND SIDES OF LINEAR SYSTEM
C
        TYPE(BIEF_OBJ), TARGET :: CV1, CV2, CV3,CV1S
C
C       RIGHT HAND SIDE OF CONTINUITY EQUATION
C
        TYPE(BIEF_OBJ), TARGET :: SMH
C
C       P0 WORKING ARRAYS, W1 WITH A SECOND DIMENSION
C       TE4 AND TE5 FOR OPTION 3 OF TREATMENT OF TIDAL FLATS
C       MSKSEC FOR FLUXES ACCROSS SECTIONS
        TYPE(BIEF_OBJ), TARGET :: TE1,TE2,TE3,TE4,TE5,W1,MSKSEC
        TYPE(BIEF_OBJ), TARGET :: ZFLATS
C
C       FRICTION COEFFICIENT, IN TERMS OF STRICKLER, CHEZY, ETC
C
        TYPE(BIEF_OBJ), TARGET :: CHESTR
C
C       BOUNDARY CONDITIONS, INTEGER ARRAYS
C
        TYPE(BIEF_OBJ), TARGET :: LIUBOR,LIVBOR,LIHBOR,LITBOR
        TYPE(BIEF_OBJ), TARGET :: LIMTRA,LIMKEP,LIMPRO
        TYPE(BIEF_OBJ), TARGET :: CLH,CLU,CLV,BOUNDARY_COLOUR
C
C       REAL ARRAYS USED FOR LAGRANGIAN DRIFTS, DROGUES, DIKES
C
        TYPE(BIEF_OBJ), TARGET :: XFLOT,YFLOT,SHPFLO,XLAG,YLAG,SHPLAG
        TYPE(BIEF_OBJ), TARGET :: ZDIG,PHIDIG
C
C       INTEGER ARRAYS USED FOR LAGRANGIAN DRIFTS, DIKES, DROGUES
C
        TYPE(BIEF_OBJ), TARGET :: DEBFLO,FINFLO,ELTFLO,IKLFLO
        TYPE(BIEF_OBJ), TARGET :: DEBLAG,FINLAG,ELTLAG,NUMDIG
C
C       INTEGER WORKING ARRAYS
C
        TYPE(BIEF_OBJ), TARGET :: IT1,IT2,IT3,IT4
C
C       REAL ARRAYS FOR BOUSSINESQ AND FINITE VOLUMES 
C
        TYPE(BIEF_OBJ), TARGET :: QU,QV
        TYPE(BIEF_OBJ), TARGET :: HSTOK,SMTR,LOGFR,HCSTOK,FLUXT,HT
        TYPE(BIEF_OBJ), TARGET :: HC,DSZ,FLUXTEMP,FLUHBTEMP,FLUHBOR
C
C       FOR MASKING AND TIDAL FLATS
C
        TYPE(BIEF_OBJ), TARGET :: SECMOU , MASKEL , MASKPT , IFAMAS
C
C       FOR NUMBERING LIQUID BOUNDARIES
C
        TYPE(BIEF_OBJ), TARGET :: NUMLIQ
C
C       FOR MAXIMUM ELEVATIONS AND VELOCITIES AND CORRESPONDING TIMES
C
        TYPE(BIEF_OBJ), TARGET :: MAXZ,TMAXZ,MAXV,TMAXV
C
C       FOR STORING ZONE NUMBERS
C
        TYPE(BIEF_OBJ), TARGET :: ZONE
C
C       FOR STORING RESULTS OF FOURIER ANALYSIS
C
        TYPE(BIEF_OBJ), TARGET :: AMPL,PHAS
C
C       CHESTR FOR BOUNDARY CONDITIONS
C
        TYPE(BIEF_OBJ),TARGET :: CHBORD
C
C       FOR DELWAQ
C
        TYPE(BIEF_OBJ),TARGET :: UDEL,VDEL,DM1,ZCONV,FLODEL,FLULIM
C
C       EXPLICIT AND IMPLICIT SOURCE TERMS FOR TRACERS
C
        TYPE(BIEF_OBJ),TARGET :: TEXP,TIMP,TSCEXP
C
C-----------------------------------------------------------------------
C
C       2) MATRICES
C
C-----------------------------------------------------------------------
C
C       MATRICES
C
C       SYSTEM SOLVED IN PROPAG WILL BE :
C
C     ( AM1  BM1  BM2 )   (DH)      ( CV1 )
C     (               )   (  )      (     )
C     ( CM1  AM2  A23 )   (U )  =   ( CV2 )          
C     (               )   (  )      (     )
C     ( CM2  A32  AM3 )   (V )      ( CV3 )
C
C
        TYPE(BIEF_OBJ), TARGET :: AM1,AM2,AM3,BM1,BM2,BM1S,BM2S
        TYPE(BIEF_OBJ), TARGET :: CM1,CM2,A23,A32,TM1,MBOR
C 
C-----------------------------------------------------------------------
C
C       3) BLOCKS
C
C-----------------------------------------------------------------------
C
C       BLOCK FOR DIRICHLET VALUES HBOR, UBOR AND VBOR
C
        TYPE(BIEF_OBJ), TARGET :: DIRBOR
C
C       BLOCK OF MASKS
C
        TYPE(BIEF_OBJ), TARGET :: MASK
C
C       BLOCK OF WORKING ARRAYS
C
        TYPE(BIEF_OBJ), TARGET :: TB
C
C       BLOCK OF PRIVATE VECTORS
C
        TYPE(BIEF_OBJ), TARGET :: PRIVE
C
C       BLOCKS OF VARIABLES AT TIME N+1, N AND RESULTS OF ADVECTION
C
        TYPE(BIEF_OBJ), TARGET :: F, FN, FTILD, FNCAR
C
C       BLOCKS OF MATRICES, RIGHT HAND SIDES AND UNKNOWNS
C       FOR LINEAR SYSTEMS
C
        TYPE(BIEF_OBJ), TARGET :: MAT,RHS,UNK
C
C       BLOCK OF CLANDEST INE VARIABLES
C
        TYPE(BIEF_OBJ), TARGET :: VARCL
C
C       BLOCK OF VARIABLES FOR OUTPUT
C
        TYPE(BIEF_OBJ), TARGET :: VARSOR
C
C-----------------------------------------------------------------------
C
C       4) INTEGERS
C
C-----------------------------------------------------------------------
C
C       KEY-WORDS AND PARAMETERS
C
C       MAXIMUM DE POINTS SOURCES
        INTEGER, PARAMETER :: MAXSCE = 100
C       MAXIMUM DE (NOMBRE DE FRONTIERES LIQUIDES, NOMBRE DE FRONTIERES SOLIDES)
        INTEGER, PARAMETER :: MAXFRO = 300
C       MAXIMUM DE VARIABLES DE SORTIE
        INTEGER, PARAMETER :: MAXVAR = 100
C       MAXIMUM DE TRACEURS
        INTEGER, PARAMETER :: MAXTRA = 20
C       NOMBRE DE POINTS POUR LES SECTIONS DE CONTROLE
        INTEGER NCP
C       ARRAY CONTAINING THE GLOBAL NUMBER OF POINTS OF CONTROL SECTIONS
        INTEGER, ALLOCATABLE :: CTRLSC(:)
C
C       MAXIMUM RANK OF LOGICAL UNITS AS DECLARED IN SUBMIT STRINGS IN THE DICTIONARY
        INTEGER, PARAMETER :: MAXLU_T2D = 47 ! jaj 44->46  jmh 46->47
C
C       SINGULARITIES (WEIRS, ETC.)
C
C       MAXIMUM NUMBER OF POINTS ON ONE SIDE OF A SINGULARITY (READ IN THE DATA)
        INTEGER NPSMAX
C       MAXIMUM NUMBER OF SINGULARITIES
        INTEGER, PARAMETER :: NWRMAX = 10
        INTEGER NPSING(NWRMAX)
C
C       FILES NUMBERS WITHIN TELEMAC-2D (FORTRAN INTEGER HAS THE SAME NAME AS
C                                        THE FILE IN THE TEMPORARY DIRECTORY)
        INTEGER T2DGEO,T2DCLI,T2DPRE,T2DRES,T2DFON
        INTEGER T2DBI1,T2DBI2,T2DFO1,T2DFO2,T2DRBI
        INTEGER T2DRFO,T2DREF,T2DIMP,T2DCOF,T2DDL1
        INTEGER T2DDL2,T2DDL3,T2DDL4,T2DDL5,T2DDL6
        INTEGER T2DDL7,T2DDL8,T2DDL9,T2DL10,T2DL11
        INTEGER T2DMAB,T2DVEF,T2DSEC,T2DSEO,T2DMIG
C
C       PERIODE POUR LES SORTIES GRAPHIQUES, GRAPHIC PRINTOUT PERIOD
C
        INTEGER LEOPRD
C
C       PERIODE DE SORTIE LISTING, LISTING PRINTOUT PERIOD
C
        INTEGER LISPRD
C
C       NOMBRE DE PAS DE TEMPS, NUMBER OF TIME STEPS
C
        INTEGER NIT
C
        INTEGER ICONVC
        INTEGER ICONVF(4)
        INTEGER ICONVI
C
C       MODELE DE TURBULENCE, TURBULENCE MODEL
C
        INTEGER ITURB
C
C       LOI DE FROTTEMENT SUR LE FOND, LAW OF BOTTOM FRICTION
C
        INTEGER KFROT
C
C       NUMBER OF SUB-ITERATIONS FOR NON-LINEARITIES
C
        INTEGER NSOUI
C
C       NOT USED (OPTION DE PROPAGATION)
C
        INTEGER OPTPRO
C 
        INTEGER IORDRH,IORDRU,NSOUSI,PTINIG,PTINIL,LISRUG
        INTEGER NDEBIT,NCOTE,NVITES,NTRACE,NVARCL,LVMAC,OPTBAN
        INTEGER NFLOT,FLOPRD,NITFLO,NLAG,LISFON,DISCRE(4),NREJET,NREJEU
        INTEGER NREJTR,OPTSUP(4),OPTHYB(4),MARDAT(3),MARTIM(3)
        INTEGER IELM0,IELM1,IELMH,IELMU,IELMT,IELMK,IELME,OPTASS
        INTEGER PRODUC,NWEIRS,NSIPH,NTYPFR
        INTEGER FRTYPE(MAXFRO),SOLSYS,PROVEL(MAXFRO)
        INTEGER NFRLIQ,NFRSOL,DEBLIQ(MAXFRO),FINLIQ(MAXFRO)
        INTEGER DEBSOL(MAXFRO),FINSOL(MAXFRO)
        INTEGER ISCE(MAXSCE),ENTSIP(MAXSCE/2),SORSIP(MAXSCE/2)
        INTEGER OPDTRA,OPDVIT,OPTSOU,NPRIV,WAQPRD,OPT_HNEG
C
C       CURRENT ITERATION NUMBER
C
        INTEGER LT
C
C       RECORD NUMBER IN THE WAVE DRIVEN CURRENTS FILE
C
        INTEGER NPTH
C
C       NUMBER OF USER-DEFINED ZONES (E.G. FOR SETTING FRICTION)
C       USER-DEFINED IN SUBROUTINE DEF_ZONES
C
        INTEGER NZONE
C
C       NUMBER OF PERIODS FOR FOURIER ANALYSIS
C
        INTEGER NPERIAF
C
C       OPTION FOR PARAMETER ESTIMATION
C
        INTEGER OPTID
C
C       NUMBER AND LIST OF REMARKABLE POINTS
C
        INTEGER NPTS,LIST_PTS(100)
C
C       CHOICE OF COST-FUNCTION, MAX. NUMB. OF ITER. FOR IDENTIFICATION
C
        INTEGER OPTCOST,MAXEST
C
C       COUPLING PERIOD
C
        INTEGER PERCOU
C
C       FINITE VOLUME SCHEME
C
        INTEGER OPTVF
C
C       ORIGIN COORDINATES
C
        INTEGER I_ORIG,J_ORIG
C
C       NUMBER OF TRACERS, NUMBER FOR TEMPERATURE, NUMBER FOR SALINITY 
C
        INTEGER NTRAC,IND_T,IND_S
C
C       NUMBER OF POINTS GIVEN FOR EACH DISCHARGE-ELEVATIONS CURVES
C       OPTION FOR TREATING STAGE-DISCHARGE CURVES
C
        INTEGER PTS_CURVES(MAXFRO)
        INTEGER STA_DIS_CURVES(MAXFRO)
C 
C       KEY-WORD DEBUGGER
        INTEGER DEBUG
C       KEY-WORD 'DEPTH IN FRICTION TERMS'
        INTEGER HFROT
C
C-----------------------------------------------------------------------
C
C       5) LOGICAL VALUES
C
C-----------------------------------------------------------------------
C
        LOGICAL DEBU  , LISTIN , DIFVIT , ATMOS ,CONV  ,CONVV(4)
        LOGICAL DIFT  , PROPA  , CORIOL , VENT   , INFOGR,BILMAS,CLIPH
        LOGICAL SPHERI, PROLIN , VALID  , INFOKE , VERLIM,CORCON,RAZTIM
        LOGICAL MSK   , STOPER , MSKUSE , SORLEO(MAXVAR),SORIMP(MAXVAR)
        LOGICAL ROVAR , MAREE  , THOMFR , PRECCU ,DTVARI,BANDEC
        LOGICAL ENTET , SPILL_MODEL
C
C       WAVE DRIVEN CURRENTS TAKEN INTO ACCOUNT
C
        LOGICAL COUROU
C
C       VERTICAL STRUCTURES TAKEN INTO ACCOUNT
C
        LOGICAL VERTIC
C
C       OUTPUT INITIAL CONDITIONS 
C
        LOGICAL OUTINI
C
C       DEFZON : IF YES, THE USER WANTS TO DEFINE ZONES 
C
        LOGICAL DEFZON
C
C       FLUXES THROUGH SECTIONS
C
        LOGICAL COMFLU,CUMFLO
C
C       OUTPUT OF SALINITY AND TEMPERATURE FOR DELWAQ
C
        LOGICAL SALI_DEL,TEMP_DEL,VELO_DEL,DIFF_DEL
C
C-----------------------------------------------------------------------
C
C       6) REALS
C
C-----------------------------------------------------------------------
C
C       PAS DE TEMPS
C
        DOUBLE PRECISION DT
C
C       ACCELERATION DE LA PESANTEUR
C
        DOUBLE PRECISION GRAV
C
C       COEFFICIENT DE FROTTEMENT, FRICTION COEFFICIENT
C
        DOUBLE PRECISION FFON
C
C       COEFFICIENT DE CORIOLIS
C
        DOUBLE PRECISION FCOR
C
C       COEFFICIENT D'INFLUENCE DU VENT, COEFFICIENT OF WIND INFLUENCE
C
        DOUBLE PRECISION FAIR
        DOUBLE PRECISION FUAIR,FVAIR
        DOUBLE PRECISION TRAC0(MAXTRA) , DIFNU 
        DOUBLE PRECISION TETAT , PROPNU , BORNES(8)
        DOUBLE PRECISION EPSOUI , TETAC , TETAU
        DOUBLE PRECISION TETAD,AGGLOC,AGGLOU,HMIN,REDUC
        DOUBLE PRECISION HAULIN , ROEAU , LAMBD0 , SB , COTINI , HAUTIN
        DOUBLE PRECISION DEBIT(MAXFRO),COTE(MAXFRO)
        DOUBLE PRECISION VITES(MAXFRO),TRACER(MAXFRO*MAXTRA)
        DOUBLE PRECISION FLUX_BOUNDARIES(MAXFRO)
        DOUBLE PRECISION XSCE(MAXSCE) ,YSCE(MAXSCE)
!       DSCE  : DEBITS DES SOURCES DU FICHIER DES PARAMETRES
!       DSCE2 : DEBITS DES SOURCES AVEC VARIATIONS EN TEMPS
        DOUBLE PRECISION DSCE(MAXSCE),DSCE2(MAXSCE)
!       TSCE  : TRACEURS DES SOURCES DU FICHIER DES PARAMETRES
!       TSCE2 : TRACEURS DES SOURCES AVEC VARIATIONS EN TEMPS
        DOUBLE PRECISION TSCE(MAXSCE,MAXTRA),TSCE2(MAXSCE,MAXTRA)
        DOUBLE PRECISION USCE(MAXSCE) ,VSCE(MAXSCE)
        DOUBLE PRECISION SECSCE(MAXSCE),CSSCE(MAXSCE),ALTSCE(MAXSCE)
        DOUBLE PRECISION CESCE(MAXSCE)
        DOUBLE PRECISION DELSCE(MAXSCE),ANGSCE(MAXSCE),LSCE(MAXSCE)
        DOUBLE PRECISION COSUPG(4),CRIPER(3),TMOY,NORD,ELDER(2),PHI0
        DOUBLE PRECISION AGGLOT,DUREE,CFLWTD,HWIND,HNEG,TETAZCOMP
        DOUBLE PRECISION TAFBGN,TAFEND
C
C       CURRENT TIME
C
        DOUBLE PRECISION AT
C
C       FOR STORING THE PERIODS FOR FOURIER ANALYSIS
C
        DOUBLE PRECISION PERIAF(50)
C
C       ARRAY OF REALS FOR READING INTO SELAFIN FILES
C
        REAL, ALLOCATABLE :: W(:)
C
C       TOLERANCES FOR IDENTIFICATION
C
        DOUBLE PRECISION TOLEST(4)
C
C       FOR STORING DISCHARGE-ELEVATION CURVES
C
        DOUBLE PRECISION, ALLOCATABLE :: QZ(:,:,:)
C
C-----------------------------------------------------------------------
C
C       7) STRINGS
C
C-----------------------------------------------------------------------
C
        CHARACTER*72 TITCAS,VARDES,VARIMP,CDTINI
        CHARACTER*20 EQUA
        CHARACTER*32 VARCLA(10),TEXTE(MAXVAR),TEXTPR(MAXVAR)
C       NAMES OF REMARKABLE POINTS
        CHARACTER*32 NAME_PTS(100)
C       NAMES OF TRACERS
        CHARACTER(LEN=32) NAMETRAC(MAXVAR)
C
C-----------------------------------------------------------------------
C
C       8) SLVCFG STRUCTURES
C
C-----------------------------------------------------------------------
C
        TYPE(SLVCFG) :: SLVPRO,SLVK,SLVEP,SLVTRA
C
C-----------------------------------------------------------------------
C
C       9) MESH STRUCTURE
C
C-----------------------------------------------------------------------
C
        TYPE(BIEF_MESH) :: MESH
C
C-----------------------------------------------------------------------
C
C      10) ALIASES
C
C-----------------------------------------------------------------------
C
C       DECLARATION OF POINTERS FOR ALIASES.
C       TARGETS ARE DEFINED IN POINT_TELEMAC2D.
C
C       ALIASES FOR WORKING VECTORS IN TB
C
        TYPE(BIEF_OBJ),POINTER :: T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12
C
C       ALIASES FOR VECTORS IN BLOCK PRIVE
C
        DOUBLE PRECISION,POINTER :: PRIVE1(:),PRIVE2(:)
        DOUBLE PRECISION,POINTER :: PRIVE3(:),PRIVE4(:)
C
C       USEFUL COMPONENTS IN STRUCTURE MESH
C
C       CONNECTIVITY TABLE
C
        TYPE(BIEF_OBJ), POINTER :: IKLE
C
C       COORDINATES
C
        DOUBLE PRECISION, DIMENSION(:), POINTER :: X,Y
C
C       NUMBER OF ELEMENTS IN THE MESH
C 
        INTEGER, POINTER        :: NELEM
C
C       MAXIMUM NUMBER OF ELEMENTS IN THE MESH
C 
        INTEGER, POINTER        :: NELMAX
C
C       NUMBER OF BOUNDARY POINTS IN THE MESH
C 
        INTEGER, POINTER        :: NPTFR
C
C       MAXIMUM NUMBER OF BOUNDARY POINTS IN THE MESH
C 
        INTEGER, POINTER        :: NPTFRX
C
C       DIMENSION OF SPACE
C 
        INTEGER, POINTER        :: DIM
C
C       TYPE OF ELEMENT
C 
        INTEGER, POINTER        :: TYPELM
C
C       NUMBER OF POINTS IN THE MESH
C 
        INTEGER, POINTER        :: NPOIN
C
C       MAXIMUM NUMBER OF POINTS IN THE MESH
C 
        INTEGER, POINTER        :: NPMAX
C
C       MAXIMUM NUMBER OF POINTS NEIGHBOURS OF A POINT
C 
        INTEGER, POINTER        :: MXPTVS
C
C       MAXIMUM NUMBER OF ELEMENTS NEIGHBOURS OF A POINT
C 
        INTEGER, POINTER        :: MXELVS
C
C       VECTOR LENGTH OF THE MACHINE
C 
        INTEGER, POINTER        :: LV
C
C=======================================================================
C
C       DECLARATIONS AJOUTEES POUR L'IDENTIFICATION DE PARAMETRES
C
C
C-----------------------------------------------------------------------
C
C       1) VECTORS
C
C-----------------------------------------------------------------------
C
C       ADJOINT VARIABLES
C
        TYPE(BIEF_OBJ), TARGET :: PP, QQ, RR
C
C       MEASURES
C
        TYPE(BIEF_OBJ), TARGET :: UD, VD, HD
C
C       DIRECT VARIABLES AT ITERATION IT (UU) AND IT+1 (UIT1)
C
        TYPE(BIEF_OBJ), TARGET :: UU, VV, HH, UIT1, VIT1, HIT1
C
C       BOUNDARY VALUES FOR ADJOINT VARIABLES (ONLY DIRICHLET)
C
        TYPE(BIEF_OBJ), TARGET :: PBOR,QBOR,RBOR
C
C       WEIGHS, STRICKLERS , GRADIENT
C
        TYPE (BIEF_OBJ) :: DESC,GRADJ,GRADJN
        TYPE (BIEF_OBJ) :: SETSTR,SETSTR2
        TYPE (BIEF_OBJ) :: ALPHA1,ALPHA2,ALPHA3
C
C
C-----------------------------------------------------------------------
C
C       2) MATRICES
C
C-----------------------------------------------------------------------
C
C       MATRICES
C
C       SYSTEM SOLVED IN PROPAG WILL BE :
C
C     ( TAM1  TCM1  TCM2 )   (PP )      ( CV1 )
C     (                  )   (   )      (     )
C     ( TBM1  TAM2  A23  )   (QQ )  =   ( CV2 )          
C     (                  )   (   )      (     )
C     ( TBM2  A32   TAM3 )   (RR )      ( CV3 )
C
C
C PAY ATTENTION TO CV1, ...
C             I USE THE SAME SYMBOLS OF THE RIGHT HAND SIDE OF DIRECT
C             SYSTEM.
C
        TYPE(BIEF_OBJ), TARGET :: TAM1,TAM2,TAM3,TBM1,TBM2
        TYPE(BIEF_OBJ), TARGET :: TCM1,TCM2
C 
C-----------------------------------------------------------------------
C
C       3) BLOCKS
C
C-----------------------------------------------------------------------
C
C       BLOCKS OF MATRICES, RIGHT HAND SIDES AND UNKNOWNS
C       FOR LINEAR SYSTEMS
C
        TYPE(BIEF_OBJ), TARGET :: MATADJ,UNKADJ

C       BLOCK OF VARIABLES FOR OUTPUT
C       VARSORA=ADJOINT VARIABLES
C
        TYPE(BIEF_OBJ), TARGET :: VARSORA
C
C       BLOCK OF DIRICHLET CONDITION FOR ADJOINT VARIABLES
        TYPE(BIEF_OBJ), TARGET :: ADJDIR
C
C-----------------------------------------------------------------------
C
C       4) INTEGERS
C
C     NUMBER OF VARIABLES FOR LITENR (READ BY SKIPGEO)
C
      INTEGER NVARRES
C
C     NUMBER OF ITERATIONS FOR PARAMETERS CALIBRATION
C
      INTEGER NITERA
C
C-----------------------------------------------------------------------
C
C        5) LOGICALS
C
C     ADJO=TRUE ACTIVATES THE ADJOINT SYSTEM IN TELEMAC2D/PROPAG
      LOGICAL ADJO
C     SORLEOA IS TO PRINT THE ADJOINT SYSTEM RESULTS
C     NB 100=MAXVAR
      LOGICAL SORLEOA(100)
      LOGICAL SORIMPA(100)
C
C-----------------------------------------------------------------------
C
C       6) STRINGS
C
C-----------------------------------------------------------------------
C
C     NAMES OF VARIABLES IN RES FILE, RBI FILE, REF FILE
C
      CHARACTER(LEN=32) TEXRES(100),TEXRBI(100),TEXREF(100)
C
C     KEY-WORD "PARAMETER ESTIMATION"
C
      CHARACTER(LEN=72) ESTIME
C
C=======================================================================
C      
      CHARACTER(LEN=144) SUBMIT(4,300)
C
C-----------------------------------------------------------------------
C
C       7) FRICTION DEFINITION BY ZONE
C
C-----------------------------------------------------------------------
C
      TYPE(FRICTION_OBJ), TARGET :: FRTAB
      TYPE(BIEF_OBJ),     TARGET :: KFROPT, NKFROT
      TYPE(BIEF_OBJ),     TARGET :: NDEFMA, LINDDP, LINDSP
      TYPE(BIEF_OBJ),     TARGET :: NDEF_B, KFRO_B
      INTEGER                    :: NZONES, NZONMX
      LOGICAL                    :: LINDNER
      LOGICAL                    :: FRICTB
      DOUBLE PRECISION           :: NDEF, DP, SP
C
C
C-----------------------------------------------------------------------
C
C      8) TELEMAC-2D FILES
C
C-----------------------------------------------------------------------
C
      TYPE(BIEF_FILE) :: T2D_FILES(MAXLU_T2D) 
C
C-----------------------------------------------------------------------
C !jaj #### 
C      9) sections
C
C-----------------------------------------------------------------------
C
      TYPE (CHAIN_TYPE), ALLOCATABLE :: CHAIN(:)
C
      SAVE
C
      END MODULE DECLARATIONS_TELEMAC2D
